version: '3.8'

services:
  feed:
    build:
      context: ../
      dockerfile: module-feed/Dockerfile
    container_name: pet-manager-feed
    restart: always
    ports:
      - "8082:8082"
    env_file:  # 이곳에서 .env 파일을 읽어 옵니다.
      - .env
    environment:
      # 변수로 대체
      SPRING_DATASOURCE_URL: ${FEED_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${FEED_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${FEED_DB_PASS}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASS}
    networks:
      - pet-manager-network

networks:
  pet-manager-network:
    external: true
    name: pet-manager-network
