version: '3.8'

services:
  feed:
    build:
      context: ../
      dockerfile: module-feed/Dockerfile
    container_name: pet-manager-feed
    restart: always
    ports:
      - "8082:8082"
    env_file:  # 이곳에서 .env 파일을 읽어 옵니다.
      - .env
    environment:

      SPRING_DATA_MONGODB_URI: ${MONGODB_URI}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASS}
    networks:
      - pet-manager-network

networks:
  pet-manager-network:
    external: true
    name: pet-manager-network
